### ISSUE TITLE
Benchmark against Frequent Directions

### ISSUE THREAD

**Issue by andyzfchen** [andyzfchen/truncatedSVD#2]
Efficient Frequent Directions Algorithm for Sparse Matrices
Mina Ghashami, Edo Liberty, Jeff M. Phillips
https://arxiv.org/abs/1602.00412

Edo Liberty and Mina Ghashami source code for Frequent Directions
https://github.com/edoliberty/frequent-directions

**Comment by andyzfchen** [comment]
- [ ] Understand FD covariance error and projection error
- [ ] Implement brute force, naive, sampling, hashing, and random-projection methods for comparison

**Comment by matsumotosan** [comment]
A couple more.

- [ ] run experiments with different k (paper does 25,50,100)
- [ ] calculate projection error (based on FD paper)
