### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by HaoranDeng** [andyzfchen/truncatedSVD#7]
Hello, I tried your code but the data could not be downloaded from google drive in the link due to permission issues. Is it possible to share the datasets CISI, CRAN and MED used for the experiment? Thanks a lot.

**Comment by matsumotosan** [comment]
I've updated the permissions, so you should be able to access the datasets.

**Comment by HaoranDeng** [comment]
My problem has been solved. Thank you very much.
